#ifndef UFBP_COMMON_HPP_
#define UFBP_COMMON_HPP_

#define UFBP_SERVER_PORT 7752
#define UFBP_CLIENT_PORT 7753

#define UFBP_SERVER_TCP_PORT 17752

#define BUFFER_SIZE 2*1024*1024
#define PACKTYPE_LENGTH 4

#endif // UFBP_COMMON_HPP_
